# Generated by Django 3.0.5 on 2020-05-03 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import system.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_zip', models.IntegerField()),
                ('loc_name', models.CharField(choices=[('SAN JOSE', 'SAN JOSE'), ('LOS ANGELES', 'LOS ANGELES'), ('SUNNYVALE', 'SUNNYVALE')], max_length=20)),
                ('address', models.TextField()),
                ('vehicle_cap', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Drivers_name', models.CharField(max_length=100, unique=True)),
                ('license_number', models.CharField(max_length=100)),
                ('cell_no', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date', models.DateTimeField()),
                ('to', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StartSubscribe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, unique=True)),
                ('start_date', models.DateField()),
                ('payment_type', models.CharField(max_length=10)),
                ('credit_card_number', models.IntegerField()),
                ('credit_card_name', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('acc', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_account', models.IntegerField()),
                ('company_account', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30)),
                ('mobileno', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=10)),
                ('license_place', models.CharField(max_length=30)),
                ('payment_type', models.CharField(max_length=10)),
                ('credit_card_number', models.IntegerField()),
                ('credit_card_name', models.CharField(max_length=30)),
                ('expiry_date', models.DateField()),
                ('cvv', models.IntegerField()),
                ('acc', models.IntegerField(default=0)),
                ('sub_start', models.DateTimeField(default=0)),
                ('sub_end', models.DateTimeField(default=0)),
                ('first_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobileno', models.IntegerField()),
                ('birthdate', models.DateField()),
                ('address', models.CharField(max_length=30)),
                ('license_number', models.CharField(max_length=10)),
                ('license_place', models.CharField(max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=system.models.uploaded_location)),
                ('make', models.CharField(max_length=100)),
                ('car_type', models.CharField(choices=[('SMALL CAR', 'SMALL CAR'), ('FULL-SIZE CAR', 'FULL-SIZE CAR'), ('TRUCK', 'TRUCK'), ('LUXURY', 'LUXURY')], max_length=50)),
                ('year', models.CharField(max_length=50)),
                ('reg_tag', models.CharField(max_length=100)),
                ('cur_milage', models.IntegerField()),
                ('last_serv', models.IntegerField()),
                ('cost_opt', models.CharField(choices=[('PER HOUR', 'PER HOUR'), ('1 - 5 HOURS', '1 - 5 HOURS'), ('6 - 10 HOURS', '6 - 10 HOURS'), ('PER DAY', 'PER DAY')], max_length=50)),
                ('cost', models.IntegerField(default=0)),
                ('zipcode', models.CharField(max_length=50)),
                ('late_fee', models.IntegerField(default=0)),
                ('booking_status', models.CharField(default='available', max_length=50)),
                ('subscription_charge', models.IntegerField(default=0)),
                ('vehicle_cond', models.CharField(choices=[('Good', 'Good'), ('Need Cleaning', 'Need Cleaning'), ('Needs Maintenance', 'Need Maintenance')], max_length=100)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle', to='system.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=50)),
                ('user_tran', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('depot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depot', to='system.Location')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='system.Car')),
            ],
        ),
    ]
